services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4173:4173"
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
  client:
    image: nginx
    ports:
      - 3080:80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    restart: unless-stopped      
    depends_on:
      - frontend
      - backend      