FROM node:20

WORKDIR /app

COPY ./backend/package.json /app/backend/package.json

WORKDIR /app/backend

RUN npm install

COPY ./backend /app/backend
COPY ./common /app/common


RUN npm run build

CMD ["npm", "run", "start:prod"]